// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBcPJzpzJaD7DcynHXpfpcbIVkVTX3Xms',
    appId: '1:346709932222:web:593c0ae84cf2bc5e09c6ef',
    messagingSenderId: '346709932222',
    projectId: 'ecommerce-d61aa',
    authDomain: 'ecommerce-d61aa.firebaseapp.com',
    storageBucket: 'ecommerce-d61aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRz39vrIztZsk8MLzuW_kdwNLwQ3hZgWs',
    appId: '1:346709932222:android:cbd3bc43239808f109c6ef',
    messagingSenderId: '346709932222',
    projectId: 'ecommerce-d61aa',
    storageBucket: 'ecommerce-d61aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVBqHkg4WEB6HUP5XaxnskWvupxjGWrEk',
    appId: '1:346709932222:ios:d561b5721c81c83909c6ef',
    messagingSenderId: '346709932222',
    projectId: 'ecommerce-d61aa',
    storageBucket: 'ecommerce-d61aa.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVBqHkg4WEB6HUP5XaxnskWvupxjGWrEk',
    appId: '1:346709932222:ios:d561b5721c81c83909c6ef',
    messagingSenderId: '346709932222',
    projectId: 'ecommerce-d61aa',
    storageBucket: 'ecommerce-d61aa.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBcPJzpzJaD7DcynHXpfpcbIVkVTX3Xms',
    appId: '1:346709932222:web:a9d8f5263d6f520c09c6ef',
    messagingSenderId: '346709932222',
    projectId: 'ecommerce-d61aa',
    authDomain: 'ecommerce-d61aa.firebaseapp.com',
    storageBucket: 'ecommerce-d61aa.appspot.com',
  );

}